/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package sdp.prac2;

import java.lang.reflect.Array;
import java.util.*;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class AppTest {

    //test Task 1 
 

    @Test void testTask1(){
 

        // Arrange


      List<Integer> a = Arrays.asList(6,8,10,9);


      List<Integer> b = Arrays.asList(0,1,2);





       List<Integer> c= Arrays.asList(6,7,20,9);


       List<Integer> d = Arrays.asList(1,2,3);





   // Act


       int results1 = SimpleFunctions.Task1(a, b);


       int results2 = SimpleFunctions.Task1(c, d);





        // Assert


        int expected1 = 24;


        int expected2= 36;


        assertEquals(expected1, results1);


        assertEquals(expected2, results1);





   }

   @Test void testTask2(){
    //Arrange
//test 1
    List<String> checka = Arrays.asList ("wordle", "connections", "Crossword");
    List<String> checkb = Arrays.asList (" ", "Boothill", "Feixiao", "Game", " ");

//test 2
    List<String> expecteda = Arrays.asList ("ordle", "onnections", "rossword");
    List<String> expectedb = Arrays.asList ("oothill", "eixiao", "ame");


    //act
//act 1
    List<String> resulta = SimpleFunctions.task2(checka);
//act 2
    List<String> resultb = SimpleFunctions.task2(checkb);


    //assert
//assertion 1
    assertArrayEquals(expecteda, resulta);
//assertion 2
    assertArrayEquals(expectedb, resultb);


}



    @Test

    public void testTask4() {
        // Arrange
        List<Integer> a = Arrays.asList(1, 2, 3);
        List<Integer> b = Arrays.asList(4, 5, 6);

        List<Integer> c = Arrays.asList(1, 2, 3);
        List<Integer> d = Arrays.asList(4, 5);

        // Act
        List<Integer> result1 = SimpleFunctions.Task4(a, b);
        List<Integer> result2 = SimpleFunctions.Task4(a, b);

        // Assert
        List<Integer> expected = Arrays.asList(1 * 6, 2 * 5, 3 * 4); // [6, 10, 12]
        assertEquals(expected, result1);
        assertNull(result2);
    }

    
    @Test void task3MatchingParentheses() {
        // Arrange
        String input1 = "(())";
        String input2 = "(()())";
        String input3 = "(()))(";
        String input4 = "((())";

        // Act
        boolean result1 = SimpleFunctions.Task3(input1);
        boolean result2 = SimpleFunctions.Task3(input2);
        boolean result3 = SimpleFunctions.Task3(input3);
        boolean result4 = SimpleFunctions.Task3(input4);

        // Assert
        assertTrue(result1);
        assertTrue(result2);
        assertFalse(result3);
        assertFalse(result4); // unmatched closing parenthesis
    }

    // Test by Munashe (g23M8754)
    @Test void task6RoundsNumbers() {
        // Arrange
        List<Integer> input1 = Arrays.asList(100, 200, 300);
        List<Integer> input2 = Arrays.asList(150, 250, 350);
        List<Integer> input3 = Arrays.asList(123, 456, 789);

        List<Integer> expected1 = Arrays.asList(100, 200, 300);
        List<Integer> expected2 = Arrays.asList(200, 300, 400);
        List<Integer> expected3 = Arrays.asList(200, 500, 800);

        // Act
        List<Integer> result1 = SimpleFunctions.Task6(input1);
        List<Integer> result2 = SimpleFunctions.Task6(input2);
        List<Integer> result3 = SimpleFunctions.Task6(input3);

        // Assert
        assertIterableEquals(expected1, result1);
        assertIterableEquals(expected2, result2);
        assertIterableEquals(expected3, result3);



    }

}
